### ISSUE TITLE
インラインコメントができない

### ISSUE THREAD

**Issue by tos-miyake** [rockwillj/GitHub-Plus#4]
![image](https://cloud.githubusercontent.com/assets/5566888/22230849/517e06be-e223-11e6-982e-55acdd2c754d.png)
↑の＋マークがでなくなり、コードに対してのコメントが出来ませんでした。

## 環境
![_mac_ _ _new_issue_ _rockwillj_github-plus](https://cloud.githubusercontent.com/assets/5566888/22230918/c461731e-e223-11e6-8eb8-4da137377218.png)

![image](https://cloud.githubusercontent.com/assets/5566888/22230889/964a6648-e223-11e6-9775-e7e01ef2e724.png)

**Comment by rockwillj** [comment]
バグ報告ありがとうございます！現象確認できましたのでなる早で修正いたします 🙇 
（前に同様の現象に遭遇しまして修正したつもりでしたが再発したのかも）

**Comment by tos-miyake** [comment]
対応ありがとうございます:bow:
楽しみにしております:smile:

**Comment by rockwillj** [comment]
現象について調べました。結論としては GitHub の仕様 (~~あるいはバグ~~) のようです。
拡張機能 (GitHub Plus) を無効にした状態で、手動で動作確認してみたのですが、

- 空白を無視しない → 「＋」ボタンが表示される
- 空白を無視する → 「＋」ボタンが表示されない

という結果でしたので、少なくとも拡張機能が原因という訳ではなさそうです。
`Show spaces` をチェックすると「空白を無視する」機能が一時的に無効になるので、「＋」ボタンが表示されるようになりました。
README.md に既知の問題＆回避方法として追記しておきます。

（画像付きで大変分かりやすいバグ報告ありがとうございます 😄 ）

**Comment by tos-miyake** [comment]
> 結論としては GitHub の仕様 (あるいはバグ) のようです。

そうなんですね、了解しました。`Show spaces`にチェックを入れて運用してみます。
素早いご対応ありがとうございました！！

**Comment by rockwillj** [comment]
📝 GitHub サポートへの問い合わせに対する回答 (バグではなく意図した挙動とのこと)

> Thanks for getting in touch with your question. This is intended behaviour. When viewing a diff without whitespace, the layout and line numbers of the diff can change dramatically, so we don't currently support adding a line comment in this mode. When viewed with whitespace displayed, the line comment could be on a different line.
> 
> I hope this helps explain this behaviour. Let us know if you have any other questions.
